// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const awardAchievement = `-- name: AwardAchievement :exec
INSERT INTO child_achievements (child_id, achievement_id)
VALUES ($1, $2)
ON CONFLICT (child_id, achievement_id) DO NOTHING
`

type AwardAchievementParams struct {
	ChildID       pgtype.UUID `json:"child_id"`
	AchievementID pgtype.UUID `json:"achievement_id"`
}

func (q *Queries) AwardAchievement(ctx context.Context, arg AwardAchievementParams) error {
	_, err := q.db.Exec(ctx, awardAchievement, arg.ChildID, arg.AchievementID)
	return err
}

const getAchievementByCode = `-- name: GetAchievementByCode :one
SELECT id FROM achievements WHERE code = $1
`

func (q *Queries) GetAchievementByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAchievementByCode, code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllAchievementsWithStatus = `-- name: GetAllAchievementsWithStatus :many
SELECT
  a.id,
  a.code,
  a.name,
  a.description,
  ca.earned_at
FROM achievements a
LEFT JOIN child_achievements ca ON ca.achievement_id = a.id AND ca.child_id = $1
ORDER BY a.name
`

type GetAllAchievementsWithStatusRow struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	EarnedAt    pgtype.Timestamptz `json:"earned_at"`
}

func (q *Queries) GetAllAchievementsWithStatus(ctx context.Context, childID pgtype.UUID) ([]GetAllAchievementsWithStatusRow, error) {
	rows, err := q.db.Query(ctx, getAllAchievementsWithStatus, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllAchievementsWithStatusRow{}
	for rows.Next() {
		var i GetAllAchievementsWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.EarnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLifetimePoints = `-- name: GetLifetimePoints :one
SELECT COALESCE(lifetime_earned, 0)::int AS lifetime_earned
FROM point_wallets WHERE child_id = $1
`

func (q *Queries) GetLifetimePoints(ctx context.Context, childID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getLifetimePoints, childID)
	var lifetime_earned int32
	err := row.Scan(&lifetime_earned)
	return lifetime_earned, err
}

const hasChildAchievement = `-- name: HasChildAchievement :one
SELECT EXISTS (
  SELECT 1 FROM child_achievements ca
  JOIN achievements a ON a.id = ca.achievement_id
  WHERE ca.child_id = $1 AND a.code = $2
) AS has_achievement
`

type HasChildAchievementParams struct {
	ChildID pgtype.UUID `json:"child_id"`
	Code    string      `json:"code"`
}

func (q *Queries) HasChildAchievement(ctx context.Context, arg HasChildAchievementParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasChildAchievement, arg.ChildID, arg.Code)
	var has_achievement bool
	err := row.Scan(&has_achievement)
	return has_achievement, err
}
