// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO math_questions (grade_level, topic, difficulty, question_text, options, correct_answer, explanation)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, grade_level, topic, difficulty, question_text, options, correct_answer, explanation, is_active
`

type CreateQuestionParams struct {
	GradeLevel    int32   `json:"grade_level"`
	Topic         string  `json:"topic"`
	Difficulty    int32   `json:"difficulty"`
	QuestionText  string  `json:"question_text"`
	Options       []byte  `json:"options"`
	CorrectAnswer string  `json:"correct_answer"`
	Explanation   *string `json:"explanation"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (MathQuestion, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.GradeLevel,
		arg.Topic,
		arg.Difficulty,
		arg.QuestionText,
		arg.Options,
		arg.CorrectAnswer,
		arg.Explanation,
	)
	var i MathQuestion
	err := row.Scan(
		&i.ID,
		&i.GradeLevel,
		&i.Topic,
		&i.Difficulty,
		&i.QuestionText,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.IsActive,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
UPDATE math_questions SET is_active = false WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const listAllQuestions = `-- name: ListAllQuestions :many
SELECT id, grade_level, topic, difficulty, question_text, options, correct_answer, explanation, is_active FROM math_questions ORDER BY grade_level, difficulty
`

func (q *Queries) ListAllQuestions(ctx context.Context) ([]MathQuestion, error) {
	rows, err := q.db.Query(ctx, listAllQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MathQuestion{}
	for rows.Next() {
		var i MathQuestion
		if err := rows.Scan(
			&i.ID,
			&i.GradeLevel,
			&i.Topic,
			&i.Difficulty,
			&i.QuestionText,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, email, password_hash, role, is_active, created_at, updated_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingVideos = `-- name: ListPendingVideos :many
SELECT id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at FROM videos WHERE status = 'pending' ORDER BY created_at
`

func (q *Queries) ListPendingVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listPendingVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Title,
			&i.Url,
			&i.ThumbnailUrl,
			&i.VideoType,
			&i.Scope,
			&i.ChildID,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleUserActive = `-- name: ToggleUserActive :one
UPDATE users SET is_active = NOT is_active WHERE id = $1 RETURNING id, email, password_hash, role, is_active, created_at, updated_at
`

func (q *Queries) ToggleUserActive(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, toggleUserActive, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE math_questions SET grade_level=$2, topic=$3, difficulty=$4, question_text=$5, options=$6, correct_answer=$7, explanation=$8 WHERE id=$1 RETURNING id, grade_level, topic, difficulty, question_text, options, correct_answer, explanation, is_active
`

type UpdateQuestionParams struct {
	ID            pgtype.UUID `json:"id"`
	GradeLevel    int32       `json:"grade_level"`
	Topic         string      `json:"topic"`
	Difficulty    int32       `json:"difficulty"`
	QuestionText  string      `json:"question_text"`
	Options       []byte      `json:"options"`
	CorrectAnswer string      `json:"correct_answer"`
	Explanation   *string     `json:"explanation"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (MathQuestion, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.GradeLevel,
		arg.Topic,
		arg.Difficulty,
		arg.QuestionText,
		arg.Options,
		arg.CorrectAnswer,
		arg.Explanation,
	)
	var i MathQuestion
	err := row.Scan(
		&i.ID,
		&i.GradeLevel,
		&i.Topic,
		&i.Difficulty,
		&i.QuestionText,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.IsActive,
	)
	return i, err
}
