// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role) VALUES ($1, $2, $3) RETURNING id, email, password_hash, role, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
	Role         string  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildByID = `-- name: GetChildByID :one
SELECT id, user_id, parent_id, display_name, pin_hash, grade_level, current_level, is_locked, avatar, username FROM child_profiles WHERE id = $1
`

func (q *Queries) GetChildByID(ctx context.Context, id pgtype.UUID) (ChildProfile, error) {
	row := q.db.QueryRow(ctx, getChildByID, id)
	var i ChildProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.DisplayName,
		&i.PinHash,
		&i.GradeLevel,
		&i.CurrentLevel,
		&i.IsLocked,
		&i.Avatar,
		&i.Username,
	)
	return i, err
}

const getChildByUserID = `-- name: GetChildByUserID :one
SELECT id, user_id, parent_id, display_name, pin_hash, grade_level, current_level, is_locked, avatar, username FROM child_profiles WHERE user_id = $1
`

func (q *Queries) GetChildByUserID(ctx context.Context, userID pgtype.UUID) (ChildProfile, error) {
	row := q.db.QueryRow(ctx, getChildByUserID, userID)
	var i ChildProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.DisplayName,
		&i.PinHash,
		&i.GradeLevel,
		&i.CurrentLevel,
		&i.IsLocked,
		&i.Avatar,
		&i.Username,
	)
	return i, err
}

const getChildByUsername = `-- name: GetChildByUsername :one
SELECT id, user_id, parent_id, display_name, pin_hash, grade_level, current_level, is_locked, avatar, username FROM child_profiles WHERE username = $1
`

func (q *Queries) GetChildByUsername(ctx context.Context, username string) (ChildProfile, error) {
	row := q.db.QueryRow(ctx, getChildByUsername, username)
	var i ChildProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.DisplayName,
		&i.PinHash,
		&i.GradeLevel,
		&i.CurrentLevel,
		&i.IsLocked,
		&i.Avatar,
		&i.Username,
	)
	return i, err
}

const getChildGradeLevel = `-- name: GetChildGradeLevel :one
SELECT grade_level FROM child_profiles WHERE id = $1
`

func (q *Queries) GetChildGradeLevel(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getChildGradeLevel, id)
	var grade_level int32
	err := row.Scan(&grade_level)
	return grade_level, err
}

const getParentSettings = `-- name: GetParentSettings :one
SELECT id, child_id, daily_watch_limit_minutes, conversion_rate, allowed_hours, require_study_first, min_study_minutes, emergency_lock, updated_at FROM parent_settings WHERE child_id = $1
`

func (q *Queries) GetParentSettings(ctx context.Context, childID pgtype.UUID) (ParentSetting, error) {
	row := q.db.QueryRow(ctx, getParentSettings, childID)
	var i ParentSetting
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.DailyWatchLimitMinutes,
		&i.ConversionRate,
		&i.AllowedHours,
		&i.RequireStudyFirst,
		&i.MinStudyMinutes,
		&i.EmergencyLock,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, is_active, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, is_active, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users SET is_active = $2 WHERE id = $1
`

type UpdateUserActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive *bool       `json:"is_active"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.Exec(ctx, updateUserActive, arg.ID, arg.IsActive)
	return err
}
