// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameAnswer = `-- name: CreateGameAnswer :one
INSERT INTO game_answers (session_id, question_id, submitted_answer, is_correct, points_earned, time_taken_seconds, nonce) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, session_id, question_id, submitted_answer, is_correct, points_earned, time_taken_seconds, nonce, answered_at
`

type CreateGameAnswerParams struct {
	SessionID        pgtype.UUID `json:"session_id"`
	QuestionID       pgtype.UUID `json:"question_id"`
	SubmittedAnswer  *string     `json:"submitted_answer"`
	IsCorrect        bool        `json:"is_correct"`
	PointsEarned     *int32      `json:"points_earned"`
	TimeTakenSeconds *int32      `json:"time_taken_seconds"`
	Nonce            string      `json:"nonce"`
}

func (q *Queries) CreateGameAnswer(ctx context.Context, arg CreateGameAnswerParams) (GameAnswer, error) {
	row := q.db.QueryRow(ctx, createGameAnswer,
		arg.SessionID,
		arg.QuestionID,
		arg.SubmittedAnswer,
		arg.IsCorrect,
		arg.PointsEarned,
		arg.TimeTakenSeconds,
		arg.Nonce,
	)
	var i GameAnswer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.QuestionID,
		&i.SubmittedAnswer,
		&i.IsCorrect,
		&i.PointsEarned,
		&i.TimeTakenSeconds,
		&i.Nonce,
		&i.AnsweredAt,
	)
	return i, err
}

const createGameSession = `-- name: CreateGameSession :one
INSERT INTO game_sessions (child_id) VALUES ($1) RETURNING id, child_id, total_questions, correct_count, points_earned, duration_seconds, started_at, ended_at
`

func (q *Queries) CreateGameSession(ctx context.Context, childID pgtype.UUID) (GameSession, error) {
	row := q.db.QueryRow(ctx, createGameSession, childID)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TotalQuestions,
		&i.CorrectCount,
		&i.PointsEarned,
		&i.DurationSeconds,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createNonce = `-- name: CreateNonce :exec
INSERT INTO question_nonces (nonce, child_id, question_id, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateNonceParams struct {
	Nonce      string             `json:"nonce"`
	ChildID    pgtype.UUID        `json:"child_id"`
	QuestionID pgtype.UUID        `json:"question_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateNonce(ctx context.Context, arg CreateNonceParams) error {
	_, err := q.db.Exec(ctx, createNonce,
		arg.Nonce,
		arg.ChildID,
		arg.QuestionID,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredNonces = `-- name: DeleteExpiredNonces :exec
DELETE FROM question_nonces WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredNonces(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNonces)
	return err
}

const endGameSession = `-- name: EndGameSession :one
UPDATE game_sessions SET ended_at = NOW(), total_questions = $2, correct_count = $3, points_earned = $4, duration_seconds = $5 WHERE id = $1 RETURNING id, child_id, total_questions, correct_count, points_earned, duration_seconds, started_at, ended_at
`

type EndGameSessionParams struct {
	ID              pgtype.UUID `json:"id"`
	TotalQuestions  *int32      `json:"total_questions"`
	CorrectCount    *int32      `json:"correct_count"`
	PointsEarned    *int32      `json:"points_earned"`
	DurationSeconds *int32      `json:"duration_seconds"`
}

func (q *Queries) EndGameSession(ctx context.Context, arg EndGameSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, endGameSession,
		arg.ID,
		arg.TotalQuestions,
		arg.CorrectCount,
		arg.PointsEarned,
		arg.DurationSeconds,
	)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TotalQuestions,
		&i.CorrectCount,
		&i.PointsEarned,
		&i.DurationSeconds,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getGameSession = `-- name: GetGameSession :one
SELECT id, child_id, total_questions, correct_count, points_earned, duration_seconds, started_at, ended_at FROM game_sessions WHERE id = $1
`

func (q *Queries) GetGameSession(ctx context.Context, id pgtype.UUID) (GameSession, error) {
	row := q.db.QueryRow(ctx, getGameSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.TotalQuestions,
		&i.CorrectCount,
		&i.PointsEarned,
		&i.DurationSeconds,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getNonce = `-- name: GetNonce :one
SELECT nonce, child_id, question_id, expires_at, used FROM question_nonces WHERE nonce = $1
`

func (q *Queries) GetNonce(ctx context.Context, nonce string) (QuestionNonce, error) {
	row := q.db.QueryRow(ctx, getNonce, nonce)
	var i QuestionNonce
	err := row.Scan(
		&i.Nonce,
		&i.ChildID,
		&i.QuestionID,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, grade_level, topic, difficulty, question_text, options, correct_answer, explanation, is_active FROM math_questions WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id pgtype.UUID) (MathQuestion, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i MathQuestion
	err := row.Scan(
		&i.ID,
		&i.GradeLevel,
		&i.Topic,
		&i.Difficulty,
		&i.QuestionText,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.IsActive,
	)
	return i, err
}

const getRandomQuestion = `-- name: GetRandomQuestion :one
SELECT id, grade_level, topic, difficulty, question_text, options, correct_answer, explanation, is_active FROM math_questions
WHERE grade_level = $1 AND is_active = true
ORDER BY RANDOM() LIMIT 1
`

func (q *Queries) GetRandomQuestion(ctx context.Context, gradeLevel int32) (MathQuestion, error) {
	row := q.db.QueryRow(ctx, getRandomQuestion, gradeLevel)
	var i MathQuestion
	err := row.Scan(
		&i.ID,
		&i.GradeLevel,
		&i.Topic,
		&i.Difficulty,
		&i.QuestionText,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.IsActive,
	)
	return i, err
}

const getSessionAnswers = `-- name: GetSessionAnswers :many
SELECT id, session_id, question_id, submitted_answer, is_correct, points_earned, time_taken_seconds, nonce, answered_at FROM game_answers WHERE session_id = $1
`

func (q *Queries) GetSessionAnswers(ctx context.Context, sessionID pgtype.UUID) ([]GameAnswer, error) {
	rows, err := q.db.Query(ctx, getSessionAnswers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameAnswer{}
	for rows.Next() {
		var i GameAnswer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.QuestionID,
			&i.SubmittedAnswer,
			&i.IsCorrect,
			&i.PointsEarned,
			&i.TimeTakenSeconds,
			&i.Nonce,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreak = `-- name: GetStreak :one
SELECT id, child_id, current_streak, longest_streak, last_activity_date FROM streaks WHERE child_id = $1
`

func (q *Queries) GetStreak(ctx context.Context, childID pgtype.UUID) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreak, childID)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
	)
	return i, err
}

const markNonceUsed = `-- name: MarkNonceUsed :exec
UPDATE question_nonces SET used = true WHERE nonce = $1
`

func (q *Queries) MarkNonceUsed(ctx context.Context, nonce string) error {
	_, err := q.db.Exec(ctx, markNonceUsed, nonce)
	return err
}

const upsertStreak = `-- name: UpsertStreak :one
INSERT INTO streaks (child_id, current_streak, longest_streak, last_activity_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (child_id) DO UPDATE
SET current_streak = $2, longest_streak = $3, last_activity_date = $4
RETURNING id, child_id, current_streak, longest_streak, last_activity_date
`

type UpsertStreakParams struct {
	ChildID          pgtype.UUID `json:"child_id"`
	CurrentStreak    *int32      `json:"current_streak"`
	LongestStreak    *int32      `json:"longest_streak"`
	LastActivityDate pgtype.Date `json:"last_activity_date"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) (Streak, error) {
	row := q.db.QueryRow(ctx, upsertStreak,
		arg.ChildID,
		arg.CurrentStreak,
		arg.LongestStreak,
		arg.LastActivityDate,
	)
	var i Streak
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityDate,
	)
	return i, err
}
