// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

type ChildAchievement struct {
	ID            pgtype.UUID        `json:"id"`
	ChildID       pgtype.UUID        `json:"child_id"`
	AchievementID pgtype.UUID        `json:"achievement_id"`
	EarnedAt      pgtype.Timestamptz `json:"earned_at"`
}

type ChildProfile struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	DisplayName  string      `json:"display_name"`
	PinHash      string      `json:"pin_hash"`
	GradeLevel   int32       `json:"grade_level"`
	CurrentLevel *int32      `json:"current_level"`
	IsLocked     *bool       `json:"is_locked"`
	Avatar       *string     `json:"avatar"`
	Username     string      `json:"username"`
}

type ChildVideoAssignment struct {
	ChildID    pgtype.UUID        `json:"child_id"`
	VideoID    pgtype.UUID        `json:"video_id"`
	AssignedBy pgtype.UUID        `json:"assigned_by"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type GameAnswer struct {
	ID               pgtype.UUID        `json:"id"`
	SessionID        pgtype.UUID        `json:"session_id"`
	QuestionID       pgtype.UUID        `json:"question_id"`
	SubmittedAnswer  *string            `json:"submitted_answer"`
	IsCorrect        bool               `json:"is_correct"`
	PointsEarned     *int32             `json:"points_earned"`
	TimeTakenSeconds *int32             `json:"time_taken_seconds"`
	Nonce            string             `json:"nonce"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
}

type GameSession struct {
	ID              pgtype.UUID        `json:"id"`
	ChildID         pgtype.UUID        `json:"child_id"`
	TotalQuestions  *int32             `json:"total_questions"`
	CorrectCount    *int32             `json:"correct_count"`
	PointsEarned    *int32             `json:"points_earned"`
	DurationSeconds *int32             `json:"duration_seconds"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
}

type MathQuestion struct {
	ID            pgtype.UUID `json:"id"`
	GradeLevel    int32       `json:"grade_level"`
	Topic         string      `json:"topic"`
	Difficulty    int32       `json:"difficulty"`
	QuestionText  string      `json:"question_text"`
	Options       []byte      `json:"options"`
	CorrectAnswer string      `json:"correct_answer"`
	Explanation   *string     `json:"explanation"`
	IsActive      *bool       `json:"is_active"`
}

type ParentProfile struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	FullName string      `json:"full_name"`
	Phone    *string     `json:"phone"`
}

type ParentSetting struct {
	ID                     pgtype.UUID        `json:"id"`
	ChildID                pgtype.UUID        `json:"child_id"`
	DailyWatchLimitMinutes *int32             `json:"daily_watch_limit_minutes"`
	ConversionRate         *int32             `json:"conversion_rate"`
	AllowedHours           []byte             `json:"allowed_hours"`
	RequireStudyFirst      *bool              `json:"require_study_first"`
	MinStudyMinutes        *int32             `json:"min_study_minutes"`
	EmergencyLock          *bool              `json:"emergency_lock"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type PointTransaction struct {
	ID             pgtype.UUID        `json:"id"`
	WalletID       pgtype.UUID        `json:"wallet_id"`
	Type           string             `json:"type"`
	Amount         int32              `json:"amount"`
	IdempotencyKey *string            `json:"idempotency_key"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PointWallet struct {
	ID             pgtype.UUID        `json:"id"`
	ChildID        pgtype.UUID        `json:"child_id"`
	Balance        *int32             `json:"balance"`
	LifetimeEarned *int32             `json:"lifetime_earned"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type QuestionNonce struct {
	Nonce      string             `json:"nonce"`
	ChildID    pgtype.UUID        `json:"child_id"`
	QuestionID pgtype.UUID        `json:"question_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Used       *bool              `json:"used"`
}

type Streak struct {
	ID               pgtype.UUID `json:"id"`
	ChildID          pgtype.UUID `json:"child_id"`
	CurrentStreak    *int32      `json:"current_streak"`
	LongestStreak    *int32      `json:"longest_streak"`
	LastActivityDate pgtype.Date `json:"last_activity_date"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        *string            `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	Role         string             `json:"role"`
	IsActive     *bool              `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Video struct {
	ID              pgtype.UUID        `json:"id"`
	SubmittedBy     pgtype.UUID        `json:"submitted_by"`
	Title           string             `json:"title"`
	Url             string             `json:"url"`
	ThumbnailUrl    *string            `json:"thumbnail_url"`
	VideoType       *string            `json:"video_type"`
	Scope           *string            `json:"scope"`
	Status          *string            `json:"status"`
	RejectionReason *string            `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type WatchHistory struct {
	ID                  pgtype.UUID        `json:"id"`
	ChildID             pgtype.UUID        `json:"child_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	SessionID           pgtype.UUID        `json:"session_id"`
	DurationSeconds     int32              `json:"duration_seconds"`
	WatchedAt           pgtype.Timestamptz `json:"watched_at"`
	LastPositionSeconds int32              `json:"last_position_seconds"`
}

type WatchSession struct {
	ID                  pgtype.UUID        `json:"id"`
	ChildID             pgtype.UUID        `json:"child_id"`
	VideoID             pgtype.UUID        `json:"video_id"`
	AllocatedSeconds    int32              `json:"allocated_seconds"`
	ConsumedSeconds     *int32             `json:"consumed_seconds"`
	Status              *string            `json:"status"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	LastHeartbeatAt     pgtype.Timestamptz `json:"last_heartbeat_at"`
	EndedAt             pgtype.Timestamptz `json:"ended_at"`
	LastPositionSeconds int32              `json:"last_position_seconds"`
}

type WatchWallet struct {
	ID               pgtype.UUID        `json:"id"`
	ChildID          pgtype.UUID        `json:"child_id"`
	BalanceSeconds   *int32             `json:"balance_seconds"`
	UsedTodaySeconds *int32             `json:"used_today_seconds"`
	LastResetDate    pgtype.Date        `json:"last_reset_date"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
