// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChildProfile = `-- name: CreateChildProfile :one
INSERT INTO child_profiles (user_id, parent_id, display_name, username, pin_hash, grade_level, avatar) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, parent_id, display_name, pin_hash, grade_level, current_level, is_locked, avatar, username
`

type CreateChildProfileParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	DisplayName string      `json:"display_name"`
	Username    string      `json:"username"`
	PinHash     string      `json:"pin_hash"`
	GradeLevel  int32       `json:"grade_level"`
	Avatar      *string     `json:"avatar"`
}

func (q *Queries) CreateChildProfile(ctx context.Context, arg CreateChildProfileParams) (ChildProfile, error) {
	row := q.db.QueryRow(ctx, createChildProfile,
		arg.UserID,
		arg.ParentID,
		arg.DisplayName,
		arg.Username,
		arg.PinHash,
		arg.GradeLevel,
		arg.Avatar,
	)
	var i ChildProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.DisplayName,
		&i.PinHash,
		&i.GradeLevel,
		&i.CurrentLevel,
		&i.IsLocked,
		&i.Avatar,
		&i.Username,
	)
	return i, err
}

const createChildUser = `-- name: CreateChildUser :one
INSERT INTO users (role) VALUES ('child') RETURNING id, email, password_hash, role, is_active, created_at, updated_at
`

func (q *Queries) CreateChildUser(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, createChildUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildAccuracyPerTopic = `-- name: GetChildAccuracyPerTopic :many
SELECT mq.topic,
       COUNT(*) FILTER (WHERE ga.is_correct) AS correct,
       COUNT(*) AS total
FROM game_answers ga
JOIN game_sessions gs ON gs.id = ga.session_id
JOIN math_questions mq ON mq.id = ga.question_id
WHERE gs.child_id = $1
GROUP BY mq.topic
ORDER BY mq.topic
`

type GetChildAccuracyPerTopicRow struct {
	Topic   string `json:"topic"`
	Correct int64  `json:"correct"`
	Total   int64  `json:"total"`
}

func (q *Queries) GetChildAccuracyPerTopic(ctx context.Context, childID pgtype.UUID) ([]GetChildAccuracyPerTopicRow, error) {
	rows, err := q.db.Query(ctx, getChildAccuracyPerTopic, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildAccuracyPerTopicRow{}
	for rows.Next() {
		var i GetChildAccuracyPerTopicRow
		if err := rows.Scan(&i.Topic, &i.Correct, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildAnalytics = `-- name: GetChildAnalytics :many
SELECT gs.started_at, gs.correct_count, gs.total_questions, gs.points_earned, gs.duration_seconds
FROM game_sessions gs WHERE gs.child_id = $1 AND gs.ended_at IS NOT NULL ORDER BY gs.started_at DESC LIMIT 30
`

type GetChildAnalyticsRow struct {
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CorrectCount    *int32             `json:"correct_count"`
	TotalQuestions  *int32             `json:"total_questions"`
	PointsEarned    *int32             `json:"points_earned"`
	DurationSeconds *int32             `json:"duration_seconds"`
}

func (q *Queries) GetChildAnalytics(ctx context.Context, childID pgtype.UUID) ([]GetChildAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, getChildAnalytics, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildAnalyticsRow{}
	for rows.Next() {
		var i GetChildAnalyticsRow
		if err := rows.Scan(
			&i.StartedAt,
			&i.CorrectCount,
			&i.TotalQuestions,
			&i.PointsEarned,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildrenByParentID = `-- name: GetChildrenByParentID :many
SELECT cp.id, cp.user_id, cp.parent_id, cp.display_name, cp.pin_hash, cp.grade_level, cp.current_level, cp.is_locked, cp.avatar, cp.username, u.email, u.is_active FROM child_profiles cp JOIN users u ON u.id = cp.user_id WHERE cp.parent_id = $1
`

type GetChildrenByParentIDRow struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	ParentID     pgtype.UUID `json:"parent_id"`
	DisplayName  string      `json:"display_name"`
	PinHash      string      `json:"pin_hash"`
	GradeLevel   int32       `json:"grade_level"`
	CurrentLevel *int32      `json:"current_level"`
	IsLocked     *bool       `json:"is_locked"`
	Avatar       *string     `json:"avatar"`
	Username     string      `json:"username"`
	Email        *string     `json:"email"`
	IsActive     *bool       `json:"is_active"`
}

func (q *Queries) GetChildrenByParentID(ctx context.Context, parentID pgtype.UUID) ([]GetChildrenByParentIDRow, error) {
	rows, err := q.db.Query(ctx, getChildrenByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChildrenByParentIDRow{}
	for rows.Next() {
		var i GetChildrenByParentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.DisplayName,
			&i.PinHash,
			&i.GradeLevel,
			&i.CurrentLevel,
			&i.IsLocked,
			&i.Avatar,
			&i.Username,
			&i.Email,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreakByChild = `-- name: GetStreakByChild :one
SELECT current_streak, longest_streak FROM streaks WHERE child_id = $1
`

type GetStreakByChildRow struct {
	CurrentStreak *int32 `json:"current_streak"`
	LongestStreak *int32 `json:"longest_streak"`
}

func (q *Queries) GetStreakByChild(ctx context.Context, childID pgtype.UUID) (GetStreakByChildRow, error) {
	row := q.db.QueryRow(ctx, getStreakByChild, childID)
	var i GetStreakByChildRow
	err := row.Scan(&i.CurrentStreak, &i.LongestStreak)
	return i, err
}

const getWatchHistoriesByChild = `-- name: GetWatchHistoriesByChild :many
SELECT wh.watched_at, wh.duration_seconds, v.title, v.video_type
FROM watch_histories wh
JOIN videos v ON v.id = wh.video_id
WHERE wh.child_id = $1
ORDER BY wh.watched_at DESC LIMIT 30
`

type GetWatchHistoriesByChildRow struct {
	WatchedAt       pgtype.Timestamptz `json:"watched_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	Title           string             `json:"title"`
	VideoType       *string            `json:"video_type"`
}

func (q *Queries) GetWatchHistoriesByChild(ctx context.Context, childID pgtype.UUID) ([]GetWatchHistoriesByChildRow, error) {
	rows, err := q.db.Query(ctx, getWatchHistoriesByChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWatchHistoriesByChildRow{}
	for rows.Next() {
		var i GetWatchHistoriesByChildRow
		if err := rows.Scan(
			&i.WatchedAt,
			&i.DurationSeconds,
			&i.Title,
			&i.VideoType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChildLocked = `-- name: SetChildLocked :exec
UPDATE child_profiles SET is_locked = $2 WHERE id = $1
`

type SetChildLockedParams struct {
	ID       pgtype.UUID `json:"id"`
	IsLocked *bool       `json:"is_locked"`
}

func (q *Queries) SetChildLocked(ctx context.Context, arg SetChildLockedParams) error {
	_, err := q.db.Exec(ctx, setChildLocked, arg.ID, arg.IsLocked)
	return err
}

const setEmergencyLock = `-- name: SetEmergencyLock :exec
UPDATE parent_settings SET emergency_lock = $2 WHERE child_id = $1
`

type SetEmergencyLockParams struct {
	ChildID       pgtype.UUID `json:"child_id"`
	EmergencyLock *bool       `json:"emergency_lock"`
}

func (q *Queries) SetEmergencyLock(ctx context.Context, arg SetEmergencyLockParams) error {
	_, err := q.db.Exec(ctx, setEmergencyLock, arg.ChildID, arg.EmergencyLock)
	return err
}

const updateParentSettings = `-- name: UpdateParentSettings :one
INSERT INTO parent_settings (child_id, daily_watch_limit_minutes, conversion_rate, allowed_hours, require_study_first, min_study_minutes)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (child_id) DO UPDATE
SET daily_watch_limit_minutes = $2, conversion_rate = $3, allowed_hours = $4, require_study_first = $5, min_study_minutes = $6
RETURNING id, child_id, daily_watch_limit_minutes, conversion_rate, allowed_hours, require_study_first, min_study_minutes, emergency_lock, updated_at
`

type UpdateParentSettingsParams struct {
	ChildID                pgtype.UUID `json:"child_id"`
	DailyWatchLimitMinutes *int32      `json:"daily_watch_limit_minutes"`
	ConversionRate         *int32      `json:"conversion_rate"`
	AllowedHours           []byte      `json:"allowed_hours"`
	RequireStudyFirst      *bool       `json:"require_study_first"`
	MinStudyMinutes        *int32      `json:"min_study_minutes"`
}

func (q *Queries) UpdateParentSettings(ctx context.Context, arg UpdateParentSettingsParams) (ParentSetting, error) {
	row := q.db.QueryRow(ctx, updateParentSettings,
		arg.ChildID,
		arg.DailyWatchLimitMinutes,
		arg.ConversionRate,
		arg.AllowedHours,
		arg.RequireStudyFirst,
		arg.MinStudyMinutes,
	)
	var i ParentSetting
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.DailyWatchLimitMinutes,
		&i.ConversionRate,
		&i.AllowedHours,
		&i.RequireStudyFirst,
		&i.MinStudyMinutes,
		&i.EmergencyLock,
		&i.UpdatedAt,
	)
	return i, err
}
