// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: points.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWatchTime = `-- name: AddWatchTime :one
UPDATE watch_wallets SET balance_seconds = balance_seconds + $2 WHERE child_id = $1 RETURNING id, child_id, balance_seconds, used_today_seconds, last_reset_date, updated_at
`

type AddWatchTimeParams struct {
	ChildID        pgtype.UUID `json:"child_id"`
	BalanceSeconds *int32      `json:"balance_seconds"`
}

func (q *Queries) AddWatchTime(ctx context.Context, arg AddWatchTimeParams) (WatchWallet, error) {
	row := q.db.QueryRow(ctx, addWatchTime, arg.ChildID, arg.BalanceSeconds)
	var i WatchWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BalanceSeconds,
		&i.UsedTodaySeconds,
		&i.LastResetDate,
		&i.UpdatedAt,
	)
	return i, err
}

const createPointTransaction = `-- name: CreatePointTransaction :one
INSERT INTO point_transactions (wallet_id, type, amount, idempotency_key, description) VALUES ($1, $2, $3, $4, $5) RETURNING id, wallet_id, type, amount, idempotency_key, description, created_at
`

type CreatePointTransactionParams struct {
	WalletID       pgtype.UUID `json:"wallet_id"`
	Type           string      `json:"type"`
	Amount         int32       `json:"amount"`
	IdempotencyKey *string     `json:"idempotency_key"`
	Description    *string     `json:"description"`
}

func (q *Queries) CreatePointTransaction(ctx context.Context, arg CreatePointTransactionParams) (PointTransaction, error) {
	row := q.db.QueryRow(ctx, createPointTransaction,
		arg.WalletID,
		arg.Type,
		arg.Amount,
		arg.IdempotencyKey,
		arg.Description,
	)
	var i PointTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO point_wallets (child_id) VALUES ($1) RETURNING id, child_id, balance, lifetime_earned, updated_at
`

func (q *Queries) CreateWallet(ctx context.Context, childID pgtype.UUID) (PointWallet, error) {
	row := q.db.QueryRow(ctx, createWallet, childID)
	var i PointWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.UpdatedAt,
	)
	return i, err
}

const createWatchWallet = `-- name: CreateWatchWallet :one
INSERT INTO watch_wallets (child_id) VALUES ($1) RETURNING id, child_id, balance_seconds, used_today_seconds, last_reset_date, updated_at
`

func (q *Queries) CreateWatchWallet(ctx context.Context, childID pgtype.UUID) (WatchWallet, error) {
	row := q.db.QueryRow(ctx, createWatchWallet, childID)
	var i WatchWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BalanceSeconds,
		&i.UsedTodaySeconds,
		&i.LastResetDate,
		&i.UpdatedAt,
	)
	return i, err
}

const creditPoints = `-- name: CreditPoints :one
UPDATE point_wallets SET balance = balance + $2, lifetime_earned = lifetime_earned + $2 WHERE id = $1 RETURNING id, child_id, balance, lifetime_earned, updated_at
`

type CreditPointsParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance *int32      `json:"balance"`
}

func (q *Queries) CreditPoints(ctx context.Context, arg CreditPointsParams) (PointWallet, error) {
	row := q.db.QueryRow(ctx, creditPoints, arg.ID, arg.Balance)
	var i PointWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.UpdatedAt,
	)
	return i, err
}

const deductPoints = `-- name: DeductPoints :one
UPDATE point_wallets SET balance = balance - $2 WHERE id = $1 AND balance >= $2 RETURNING id, child_id, balance, lifetime_earned, updated_at
`

type DeductPointsParams struct {
	ID      pgtype.UUID `json:"id"`
	Balance *int32      `json:"balance"`
}

func (q *Queries) DeductPoints(ctx context.Context, arg DeductPointsParams) (PointWallet, error) {
	row := q.db.QueryRow(ctx, deductPoints, arg.ID, arg.Balance)
	var i PointWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, wallet_id, type, amount, idempotency_key, description, created_at FROM point_transactions WHERE idempotency_key = $1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey *string) (PointTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i PointTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.IdempotencyKey,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletByChildID = `-- name: GetWalletByChildID :one
SELECT id, child_id, balance, lifetime_earned, updated_at FROM point_wallets WHERE child_id = $1
`

func (q *Queries) GetWalletByChildID(ctx context.Context, childID pgtype.UUID) (PointWallet, error) {
	row := q.db.QueryRow(ctx, getWalletByChildID, childID)
	var i PointWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletTransactions = `-- name: GetWalletTransactions :many
SELECT id, wallet_id, type, amount, idempotency_key, description, created_at FROM point_transactions WHERE wallet_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetWalletTransactionsParams struct {
	WalletID pgtype.UUID `json:"wallet_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) GetWalletTransactions(ctx context.Context, arg GetWalletTransactionsParams) ([]PointTransaction, error) {
	rows, err := q.db.Query(ctx, getWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PointTransaction{}
	for rows.Next() {
		var i PointTransaction
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.IdempotencyKey,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchWalletByChildID = `-- name: GetWatchWalletByChildID :one
SELECT id, child_id, balance_seconds, used_today_seconds, last_reset_date, updated_at FROM watch_wallets WHERE child_id = $1
`

func (q *Queries) GetWatchWalletByChildID(ctx context.Context, childID pgtype.UUID) (WatchWallet, error) {
	row := q.db.QueryRow(ctx, getWatchWalletByChildID, childID)
	var i WatchWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BalanceSeconds,
		&i.UsedTodaySeconds,
		&i.LastResetDate,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWalletForUpdate = `-- name: LockWalletForUpdate :one
SELECT id, child_id, balance, lifetime_earned, updated_at FROM point_wallets WHERE child_id = $1 FOR UPDATE
`

func (q *Queries) LockWalletForUpdate(ctx context.Context, childID pgtype.UUID) (PointWallet, error) {
	row := q.db.QueryRow(ctx, lockWalletForUpdate, childID)
	var i PointWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.Balance,
		&i.LifetimeEarned,
		&i.UpdatedAt,
	)
	return i, err
}

const lockWatchWalletForUpdate = `-- name: LockWatchWalletForUpdate :one
SELECT id, child_id, balance_seconds, used_today_seconds, last_reset_date, updated_at FROM watch_wallets WHERE child_id = $1 FOR UPDATE
`

func (q *Queries) LockWatchWalletForUpdate(ctx context.Context, childID pgtype.UUID) (WatchWallet, error) {
	row := q.db.QueryRow(ctx, lockWatchWalletForUpdate, childID)
	var i WatchWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BalanceSeconds,
		&i.UsedTodaySeconds,
		&i.LastResetDate,
		&i.UpdatedAt,
	)
	return i, err
}

const resetDailyWatch = `-- name: ResetDailyWatch :exec
UPDATE watch_wallets SET used_today_seconds = 0, last_reset_date = CURRENT_DATE WHERE child_id = $1
`

func (q *Queries) ResetDailyWatch(ctx context.Context, childID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetDailyWatch, childID)
	return err
}
