// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReadSession = `-- name: CreateReadSession :one
INSERT INTO read_sessions (child_id, passage_id, grade_level, transcript, accuracy, points_earned, duration_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, child_id, passage_id, grade_level, transcript, accuracy, points_earned, duration_seconds, created_at
`

type CreateReadSessionParams struct {
	ChildID         pgtype.UUID `json:"child_id"`
	PassageID       string      `json:"passage_id"`
	GradeLevel      int16       `json:"grade_level"`
	Transcript      string      `json:"transcript"`
	Accuracy        float64     `json:"accuracy"`
	PointsEarned    int32       `json:"points_earned"`
	DurationSeconds int32       `json:"duration_seconds"`
}

func (q *Queries) CreateReadSession(ctx context.Context, arg CreateReadSessionParams) (ReadSession, error) {
	row := q.db.QueryRow(ctx, createReadSession,
		arg.ChildID,
		arg.PassageID,
		arg.GradeLevel,
		arg.Transcript,
		arg.Accuracy,
		arg.PointsEarned,
		arg.DurationSeconds,
	)
	var i ReadSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.PassageID,
		&i.GradeLevel,
		&i.Transcript,
		&i.Accuracy,
		&i.PointsEarned,
		&i.DurationSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const getReadSessionCount = `-- name: GetReadSessionCount :one
SELECT COUNT(*) FROM read_sessions WHERE child_id = $1
`

func (q *Queries) GetReadSessionCount(ctx context.Context, childID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getReadSessionCount, childID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReadSessionsByChild = `-- name: GetReadSessionsByChild :many
SELECT id, child_id, passage_id, grade_level, transcript, accuracy, points_earned, duration_seconds, created_at FROM read_sessions WHERE child_id = $1 ORDER BY created_at DESC LIMIT 20
`

func (q *Queries) GetReadSessionsByChild(ctx context.Context, childID pgtype.UUID) ([]ReadSession, error) {
	rows, err := q.db.Query(ctx, getReadSessionsByChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadSession{}
	for rows.Next() {
		var i ReadSession
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.PassageID,
			&i.GradeLevel,
			&i.Transcript,
			&i.Accuracy,
			&i.PointsEarned,
			&i.DurationSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
