// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveVideo = `-- name: ApproveVideo :one
UPDATE videos SET status = 'active' WHERE id = $1 RETURNING id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at
`

func (q *Queries) ApproveVideo(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, approveVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.Title,
		&i.Url,
		&i.ThumbnailUrl,
		&i.VideoType,
		&i.Scope,
		&i.ChildID,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const closeStaleWatchSessions = `-- name: CloseStaleWatchSessions :exec
UPDATE watch_sessions SET status = 'terminated', ended_at = NOW()
WHERE status = 'active' AND last_heartbeat_at < NOW() - INTERVAL '90 seconds'
`

func (q *Queries) CloseStaleWatchSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, closeStaleWatchSessions)
	return err
}

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at
`

type CreateVideoParams struct {
	SubmittedBy  pgtype.UUID `json:"submitted_by"`
	Title        string      `json:"title"`
	Url          string      `json:"url"`
	ThumbnailUrl *string     `json:"thumbnail_url"`
	VideoType    *string     `json:"video_type"`
	Scope        *string     `json:"scope"`
	ChildID      pgtype.UUID `json:"child_id"`
	Status       *string     `json:"status"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.SubmittedBy,
		arg.Title,
		arg.Url,
		arg.ThumbnailUrl,
		arg.VideoType,
		arg.Scope,
		arg.ChildID,
		arg.Status,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.Title,
		&i.Url,
		&i.ThumbnailUrl,
		&i.VideoType,
		&i.Scope,
		&i.ChildID,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const createWatchHistory = `-- name: CreateWatchHistory :exec
INSERT INTO watch_histories (child_id, video_id, session_id, duration_seconds) VALUES ($1, $2, $3, $4)
`

type CreateWatchHistoryParams struct {
	ChildID         pgtype.UUID `json:"child_id"`
	VideoID         pgtype.UUID `json:"video_id"`
	SessionID       pgtype.UUID `json:"session_id"`
	DurationSeconds int32       `json:"duration_seconds"`
}

func (q *Queries) CreateWatchHistory(ctx context.Context, arg CreateWatchHistoryParams) error {
	_, err := q.db.Exec(ctx, createWatchHistory,
		arg.ChildID,
		arg.VideoID,
		arg.SessionID,
		arg.DurationSeconds,
	)
	return err
}

const createWatchSession = `-- name: CreateWatchSession :one
INSERT INTO watch_sessions (child_id, video_id, allocated_seconds) VALUES ($1, $2, $3) RETURNING id, child_id, video_id, allocated_seconds, consumed_seconds, status, started_at, last_heartbeat_at, ended_at
`

type CreateWatchSessionParams struct {
	ChildID          pgtype.UUID `json:"child_id"`
	VideoID          pgtype.UUID `json:"video_id"`
	AllocatedSeconds int32       `json:"allocated_seconds"`
}

func (q *Queries) CreateWatchSession(ctx context.Context, arg CreateWatchSessionParams) (WatchSession, error) {
	row := q.db.QueryRow(ctx, createWatchSession, arg.ChildID, arg.VideoID, arg.AllocatedSeconds)
	var i WatchSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.VideoID,
		&i.AllocatedSeconds,
		&i.ConsumedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.LastHeartbeatAt,
		&i.EndedAt,
	)
	return i, err
}

const deductWatchTime = `-- name: DeductWatchTime :one
UPDATE watch_wallets SET balance_seconds = balance_seconds - $2, used_today_seconds = used_today_seconds + $2 WHERE child_id = $1 AND balance_seconds >= $2 RETURNING id, child_id, balance_seconds, used_today_seconds, last_reset_date, updated_at
`

type DeductWatchTimeParams struct {
	ChildID        pgtype.UUID `json:"child_id"`
	BalanceSeconds *int32      `json:"balance_seconds"`
}

func (q *Queries) DeductWatchTime(ctx context.Context, arg DeductWatchTimeParams) (WatchWallet, error) {
	row := q.db.QueryRow(ctx, deductWatchTime, arg.ChildID, arg.BalanceSeconds)
	var i WatchWallet
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.BalanceSeconds,
		&i.UsedTodaySeconds,
		&i.LastResetDate,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos WHERE id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVideo, id)
	return err
}

const getActiveWatchSession = `-- name: GetActiveWatchSession :one
SELECT id, child_id, video_id, allocated_seconds, consumed_seconds, status, started_at, last_heartbeat_at, ended_at FROM watch_sessions WHERE child_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveWatchSession(ctx context.Context, childID pgtype.UUID) (WatchSession, error) {
	row := q.db.QueryRow(ctx, getActiveWatchSession, childID)
	var i WatchSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.VideoID,
		&i.AllocatedSeconds,
		&i.ConsumedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.LastHeartbeatAt,
		&i.EndedAt,
	)
	return i, err
}

const getAllVideos = `-- name: GetAllVideos :many
SELECT id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at FROM videos ORDER BY created_at DESC
`

func (q *Queries) GetAllVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, getAllVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Title,
			&i.Url,
			&i.ThumbnailUrl,
			&i.VideoType,
			&i.Scope,
			&i.ChildID,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalActiveVideos = `-- name: GetGlobalActiveVideos :many
SELECT id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at FROM videos WHERE scope = 'global' AND status = 'active' ORDER BY created_at DESC
`

func (q *Queries) GetGlobalActiveVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, getGlobalActiveVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Title,
			&i.Url,
			&i.ThumbnailUrl,
			&i.VideoType,
			&i.Scope,
			&i.ChildID,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideoByID(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.Title,
		&i.Url,
		&i.ThumbnailUrl,
		&i.VideoType,
		&i.Scope,
		&i.ChildID,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const getVideosByChild = `-- name: GetVideosByChild :many
SELECT id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at FROM videos WHERE (child_id = $1 OR scope = 'global') AND status = 'active' ORDER BY created_at DESC
`

func (q *Queries) GetVideosByChild(ctx context.Context, childID pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Title,
			&i.Url,
			&i.ThumbnailUrl,
			&i.VideoType,
			&i.Scope,
			&i.ChildID,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosByChildAllStatuses = `-- name: GetVideosByChildAllStatuses :many
SELECT id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at FROM videos WHERE child_id = $1 OR (scope = 'global' AND status = 'active') ORDER BY created_at DESC
`

func (q *Queries) GetVideosByChildAllStatuses(ctx context.Context, childID pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosByChildAllStatuses, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Title,
			&i.Url,
			&i.ThumbnailUrl,
			&i.VideoType,
			&i.Scope,
			&i.ChildID,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosBySubmitter = `-- name: GetVideosBySubmitter :many
SELECT id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at FROM videos WHERE submitted_by = $1 ORDER BY created_at DESC
`

func (q *Queries) GetVideosBySubmitter(ctx context.Context, submittedBy pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, getVideosBySubmitter, submittedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Title,
			&i.Url,
			&i.ThumbnailUrl,
			&i.VideoType,
			&i.Scope,
			&i.ChildID,
			&i.Status,
			&i.RejectionReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const heartbeatWatchSession = `-- name: HeartbeatWatchSession :one
UPDATE watch_sessions SET consumed_seconds = consumed_seconds + $2, last_heartbeat_at = NOW() WHERE id = $1 AND status = 'active' RETURNING id, child_id, video_id, allocated_seconds, consumed_seconds, status, started_at, last_heartbeat_at, ended_at
`

type HeartbeatWatchSessionParams struct {
	ID              pgtype.UUID `json:"id"`
	ConsumedSeconds *int32      `json:"consumed_seconds"`
}

func (q *Queries) HeartbeatWatchSession(ctx context.Context, arg HeartbeatWatchSessionParams) (WatchSession, error) {
	row := q.db.QueryRow(ctx, heartbeatWatchSession, arg.ID, arg.ConsumedSeconds)
	var i WatchSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.VideoID,
		&i.AllocatedSeconds,
		&i.ConsumedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.LastHeartbeatAt,
		&i.EndedAt,
	)
	return i, err
}

const rejectVideo = `-- name: RejectVideo :one
UPDATE videos SET status = 'rejected', rejection_reason = $2 WHERE id = $1 RETURNING id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at
`

type RejectVideoParams struct {
	ID              pgtype.UUID `json:"id"`
	RejectionReason *string     `json:"rejection_reason"`
}

func (q *Queries) RejectVideo(ctx context.Context, arg RejectVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, rejectVideo, arg.ID, arg.RejectionReason)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.Title,
		&i.Url,
		&i.ThumbnailUrl,
		&i.VideoType,
		&i.Scope,
		&i.ChildID,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}

const terminateWatchSession = `-- name: TerminateWatchSession :one
UPDATE watch_sessions SET status = $2, ended_at = NOW() WHERE id = $1 RETURNING id, child_id, video_id, allocated_seconds, consumed_seconds, status, started_at, last_heartbeat_at, ended_at
`

type TerminateWatchSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	Status *string     `json:"status"`
}

func (q *Queries) TerminateWatchSession(ctx context.Context, arg TerminateWatchSessionParams) (WatchSession, error) {
	row := q.db.QueryRow(ctx, terminateWatchSession, arg.ID, arg.Status)
	var i WatchSession
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.VideoID,
		&i.AllocatedSeconds,
		&i.ConsumedSeconds,
		&i.Status,
		&i.StartedAt,
		&i.LastHeartbeatAt,
		&i.EndedAt,
	)
	return i, err
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos SET title = $2, url = $3, thumbnail_url = $4, video_type = $5, updated_at = NOW() WHERE id = $1 RETURNING id, submitted_by, title, url, thumbnail_url, video_type, scope, child_id, status, rejection_reason, created_at
`

type UpdateVideoParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Url          string      `json:"url"`
	ThumbnailUrl *string     `json:"thumbnail_url"`
	VideoType    *string     `json:"video_type"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.ThumbnailUrl,
		arg.VideoType,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.Title,
		&i.Url,
		&i.ThumbnailUrl,
		&i.VideoType,
		&i.Scope,
		&i.ChildID,
		&i.Status,
		&i.RejectionReason,
		&i.CreatedAt,
	)
	return i, err
}
